freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script:
    - fetch ftp://ftp.freebsd.org/pub/FreeBSD/development/tarballs/ports_current.tar.gz -o /tmp/ports.tar.gz
    - tar -xf /tmp/ports.tar.gz -C /usr
    - awk -v done=0 '/# free: /{if (!done) {printf "nixbld:*:%d:\n", $3}; done=1; next} //' /usr/ports/GIDs > /tmp/GIDs && cat /tmp/GIDs > /usr/ports/GIDs
    - ln -s "${PWD}" /usr/ports/sysutils/nix
    - make -C /usr/ports/sysutils/nix all-depends-list | grep -Eo '[^/]+/[^/]+$' | xargs pkg install -y
  script:
    - make -C /usr/ports/sysutils/nix BATCH=yes stage
    - make -C /usr/ports/sysutils/nix BATCH=yes test
