freebsd_instance:
  image_family: freebsd-12-1

task:
  auto_cancellation: true
  install_script:
    - fetch ftp://ftp.freebsd.org/pub/FreeBSD/development/tarballs/ports_current.tar.gz -o /tmp/ports.tar.gz
    - tar -xf /tmp/ports.tar.gz -C /usr
    - awk -v done=0 '/# free: /{if (!done) {printf "nixbld:*:%d:\n", $3}; done=1; next} //' /usr/ports/GIDs > /tmp/GIDs && cat /tmp/GIDs > /usr/ports/GIDs
    - ln -s "${PWD}" /usr/ports/sysutils/nix
    - env ASSUME_ALWAYS_YES=yes pkg upgrade
    - env ASSUME_ALWAYS_YES=yes BATCH=yes make -C /usr/ports/devel/py-csv23 install-missing-packages install
    - env ASSUME_ALWAYS_YES=yes make -C /usr/ports/sysutils/nix install-missing-packages
  script:
    - make -C /usr/ports/sysutils/nix BATCH=yes install
    - make -C /usr/ports/sysutils/nix BATCH=yes test
