freebsd_instance:
  image_family: freebsd-12-1

task:
  auto_cancellation: true
  install_script:
    - fetch ftp://ftp.freebsd.org/pub/FreeBSD/development/tarballs/ports_current.tar.gz -o /tmp/ports.tar.gz
    - tar -xf /tmp/ports.tar.gz -C /usr
    - |-
      awk -v done=0 '/# free: /{if (!done) {printf "nixbld:*:%d:\n", $3}; done=1; next} //' /usr/ports/GIDs > /tmp/GIDs && cat /tmp/GIDs > /usr/ports/GIDs
    - ln -s "${PWD}" /usr/ports/sysutils/nix
    - mkdir -p /usr/local/etc/pkg/repos
    - |-
      echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade --yes
    - xargs pkg install -y < ./dependencies.txt
    - make -C /usr/ports/sysutils/nix BATCH=yes depends
  script:
    - make -C /usr/ports/sysutils/nix BATCH=yes install
    - make -C /usr/ports/sysutils/nix BATCH=yes test
