freebsd_instance:
  image_family: freebsd-12-1

task:
  auto_cancellation: true
  install_script:
    - fetch ftp://ftp.freebsd.org/pub/FreeBSD/development/tarballs/ports_current.tar.gz -o /tmp/ports.tar.gz
    - tar -xf /tmp/ports.tar.gz -C /usr
    - pw groupadd nixbld
    - ln -s "${PWD}" /usr/ports/sysutils/nix
    - mkdir -p /usr/local/etc/pkg/repos
    - |-
      echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg upgrade --yes
    - make -C /usr/ports/sysutils/nix all-depends-list | grep -Eo '[^/]+/[^/]+$' | xargs -n 1 pkg rquery %o | xargs pkg install -y
    - make -C /usr/ports/sysutils/nix BATCH=yes depends
  script:
    - make -C /usr/ports/sysutils/nix BATCH=yes install
    - make -C /usr/ports/sysutils/nix BATCH=yes test
